on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all 
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      # run: mvn -B package --file pom.xml
      run: |              
        mvn -f ./yaver-codegen/pom.xml clean install        

    - name: Merge jar files
      # run: mvn -B package --file pom.xml
      run: |              
        mkdir tmp
        (cd tmp; unzip -uoq ../yaver-codegen/target/yaver-codegen.jar)
        (cd tmp; unzip -uoq ../cli/openapi-generator-cli.jar)
        jar -cvf cli/yaver-generator-cli.jar -C tmp .

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./cli/yaver-generator-cli.jar
        
    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
